### ISSUE TITLE
Discrepancies in Rso Calculations: A Comparative Analysis with ASCE and FAO Standards

### ISSUE THREAD

**Issue by Gagarle** [WSWUP/agweather-qaqc#30]
Hello!
I tested the code and it works well overall. However, I noticed a discrepancy when validating the calculations. The Rso values calculated by the code are 10 to 20 units lower than those computed using the ASCE and FAO methods. This is concerning since Rso should not exhibit such a significant difference. Could you explain why this discrepancy occurs?

![image](https://github.com/WSWUP/agweather-qaqc/assets/172141281/781a236e-efe2-4d66-83cf-d622c5809b32)

**Comment by cwdunkerly** [comment]
Thank you for bringing this to my attention, I will look into it. Would you please provide the data you used to come up with these results? You can email it to me at christian.dunkerly@dri.edu

**Comment by cwdunkerly** [comment]
@Gagarle just reminding you about the data, I would like to resolve this issue if it is how you describe. 

I will close this issue in two weeks if I don't hear from you.

**Comment by cwdunkerly** [comment]
@Gagarle Thank you for sending me the data. I've looked through it and done some testing. I believe the difference between your results and agweather-qaqc are because you may be using the ASCE "simple" Rso equation (Eqs. 19 and 45 in the ASCE Reference Evapotranspiraton publication),

While agweather-qaqc uses the "full" Rso equation as described in appendix D of that same publication. The "simple" equation does not account for the effects of atmospheric water vapor so it will be higher.

I appreciate you bringing this issue up, as it's always good to have other people check the equations.
